In [2]:
import numpy as np
import pandas as pd
s = pd.Series([1,2,3,4,5],index=['a','b','c','d','e'])
print(s)
print(type(s))

a    1
b    2
c    3
d    4
e    5
dtype: int64
<class 'pandas.Series'>

In [3]:
df = pd.DataFrame({"Name":["Ahmad","Ali","Saad","Abdullah","Usman"], "Age":[21,15,22,22,25],"Marks":[87,78,85,78,89]})
df

       Name  Age  Marks
0     Ahmad   21     87
1       Ali   15     78
2      Saad   22     85
3  Abdullah   22     78
4     Usman   25     89

In [4]:
df.head(2)
df.tail(3)
df.shape
df.columns

Index(['Name', 'Age', 'Marks'], dtype='str')

In [5]:
df[["Age","Marks"]]

   Age  Marks
0   21     87
1   15     78
2   22     85
3   22     78
4   25     89

In [6]:
df.loc[1]
df.iloc[2]

Name     Saad
Age        22
Marks      85
Name: 2, dtype: object

In [7]:
df[df["Age"]<22]

    Name  Age  Marks
0  Ahmad   21     87
1    Ali   15     78

In [8]:
df["Department"]=['It','Cs','It','Eng','Math']
df

       Name  Age  Marks Department
0     Ahmad   21     87         It
1       Ali   15     78         Cs
2      Saad   22     85         It
3  Abdullah   22     78        Eng
4     Usman   25     89       Math

In [9]:
df["Age"]=df["Age"]+1
df

       Name  Age  Marks Department
0     Ahmad   22     87         It
1       Ali   16     78         Cs
2      Saad   23     85         It
3  Abdullah   23     78        Eng
4     Usman   26     89       Math

In [10]:
df.sort_values("Age",ascending=True)

       Name  Age  Marks Department
1       Ali   16     78         Cs
0     Ahmad   22     87         It
2      Saad   23     85         It
3  Abdullah   23     78        Eng
4     Usman   26     89       Math

In [11]:
df["Marks"].sum()
df["Marks"].mean()
df["Marks"].max()
df["Marks"].min()

np.int64(78)

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Name        5 non-null      str
 1   Age         5 non-null      int64
 2   Marks       5 non-null      int64
 3   Department  5 non-null      str
dtypes: int64(2), str(2)
memory usage: 292.0 bytes

In [13]:
df.iloc[2,2]

np.int64(85)

In [14]:
data = {
    "Name": ["Ali","Sara","Ahmed","Ayesha","Bilal"],
    "Age": [21,22,23,20,24],
    "City": ["Lahore","Karachi","Islamabad","Lahore","Karachi"],
    "Salary": [40000,50000,45000,38000,52000]
}

df = pd.DataFrame(data)
print(df)

     Name  Age       City  Salary
0     Ali   21     Lahore   40000
1    Sara   22    Karachi   50000
2   Ahmed   23  Islamabad   45000
3  Ayesha   20     Lahore   38000
4   Bilal   24    Karachi   52000

In [15]:
df[["Name","Salary"]]
df.iloc[1,3]
df.iloc[0:2,0:2]
df.loc[:,"City"]
df.iloc[2,3]
df.loc[3,"Age"]

np.int64(20)

In [16]:
df[(df["Age"]<23) & (df["Salary"]>40000)]

   Name  Age     City  Salary
1  Sara   22  Karachi   50000

In [17]:
df2 = pd.DataFrame(np.random.rand(50,50))
df3 = np.random.rand(50,50) < 0.2
df2[df3] = np.nan
print(df2)

          0         1         2         3         4         5         6   \
0   0.528069  0.702883  0.682178  0.237115  0.953020  0.835303  0.130616
1   0.969145  0.318191  0.832526       NaN       NaN  0.057335  0.426382
2   0.243859  0.454571  0.752819  0.413220  0.150091  0.999108       NaN
3        NaN  0.518804  0.821104  0.143476  0.885707  0.982492       NaN
4   0.603829  0.037998  0.185788       NaN  0.452775  0.736327  0.186252
5   0.128957  0.615485  0.289498  0.324988  0.981643  0.515535  0.486187
6        NaN       NaN  0.928206  0.097299  0.106138  0.564338  0.259910
7   0.711159  0.365445  0.503940  0.886966  0.529377  0.824429  0.210091
8   0.573904  0.541716  0.670184  0.482506  0.684076  0.383224       NaN
9   0.349702  0.794439  0.876504       NaN  0.468183  0.547721  0.543162
10  0.980704  0.172945  0.814023  0.677274       NaN  0.915711  0.536979
11       NaN  0.778000  0.298294  0.714916  0.745919       NaN  0.145118
12  0.358984  0.051660  0.356064  0.092112  0.632711  0.991638  0.383849
13  0.928486       NaN  0.058811  0.852552  0.364294  0.296239  0.386429
14  0.337279  0.648624  0.194927  0.655747       NaN  0.735530       NaN
15  0.284522       NaN       NaN  0.582243  0.014502  0.811469  0.827625
16  0.546236  0.318166  0.834586  0.819084  0.003623  0.955321  0.446807
17  0.439410       NaN  0.378819  0.773741  0.781102  0.037556  0.441179
18  0.863203  0.891268  0.734822  0.987289  0.866121  0.239481       NaN
19  0.372664  0.115248  0.175034  0.506282  0.463953  0.098208  0.068049
20  0.691448  0.356934  0.618258  0.332120  0.530795  0.046316  0.636992
21       NaN  0.020832  0.262642       NaN  0.127248  0.978885  0.160883
22       NaN       NaN       NaN  0.441644  0.624880  0.938996  0.530343
23  0.419253  0.661769  0.892421  0.390000  0.118799  0.505521       NaN
24  0.411758  0.943806  0.809426  0.647377  0.539430  0.985949  0.405444
25  0.798254  0.210576  0.199259  0.507624  0.019747  0.262754  0.119673
26  0.321868  0.393784       NaN  0.214424  0.312292  0.737001  0.721056
27  0.865481  0.226074  0.189233       NaN  0.858423  0.282923  0.047747
28  0.454530  0.458819  0.408472  0.621670  0.869047       NaN  0.974168
29  0.382317  0.249894       NaN       NaN  0.167929       NaN  0.850257
30  0.221964       NaN  0.164550  0.757578  0.560600       NaN       NaN
31  0.251197  0.857701  0.707747       NaN  0.475591  0.661138  0.402422
32  0.202691       NaN  0.301009  0.014619  0.631818       NaN  0.337711
33  0.696634  0.770810  0.958755  0.049295  0.034326       NaN  0.870495
34  0.675472  0.144219  0.856790  0.728971  0.957863  0.541907  0.186192
35  0.782099  0.544926  0.432340       NaN  0.227366  0.507681       NaN
36  0.562188  0.437396  0.747544       NaN  0.339475  0.904535  0.714315
37       NaN       NaN  0.743193  0.910223       NaN  0.852615       NaN
38  0.206093  0.461773  0.757107  0.584192       NaN  0.380715  0.366653
39  0.953307  0.480317  0.335948  0.240951  0.325870  0.548067  0.618302
40  0.770157  0.281357  0.871832  0.972922  0.532884  0.936571  0.652652
41  0.147705  0.890250  0.364452  0.603719  0.111046  0.011810  0.182055
42       NaN  0.425926  0.952908  0.049978       NaN  0.852051  0.922743
43  0.511132  0.732375  0.466872  0.003574       NaN       NaN  0.524752
44  0.770138  0.970164  0.653138  0.536586       NaN       NaN  0.358455
45  0.513068  0.385007  0.725959       NaN  0.834328  0.910947  0.851892
46       NaN  0.490208       NaN       NaN  0.330845  0.450868       NaN
47  0.220604  0.238899  0.909664  0.647398  0.106223  0.444784  0.437668
48  0.036057  0.294827  0.828390  0.861391  0.794032  0.665303  0.769165
49  0.322064  0.738059  0.361208  0.514775       NaN  0.098175       NaN

          7         8         9   ...        40        41        42        43  \
0   0.524680  0.881704       NaN  ...  0.674204  0.366635  0.162509  0.327565
1   0.121802  0.242109  0.782968  ...  0.588944  0.135708  0.371694  0.246413
2   0.827522  0.479972  0.437382  ...       NaN       NaN  0.948918       NaN
3   0.286869  0.031477  0.534364  ...  0.671998       NaN  0.392748  0.500406
4   0.417782  0.034315  0.220229  ...  0.568987  0.728472  0.410910  0.021686
5        NaN  0.464690  0.109306  ...  0.755103  0.058531  0.605443       NaN
6   0.704648  0.182114  0.093754  ...  0.994540  0.397942       NaN  0.506162
7   0.734409  0.311432       NaN  ...       NaN  0.067123  0.240412  0.470181
8        NaN  0.563884  0.044675  ...       NaN       NaN  0.227268  0.686267
9   0.943382  0.530688  0.475050  ...  0.030894  0.957355  0.737370  0.281558
10  0.932805  0.402551  0.367669  ...       NaN  0.149267  0.762165       NaN
11  0.797093  0.699772  0.572985  ...  0.434584       NaN  0.711700       NaN
12  0.809076  0.647604  0.625127  ...  0.391181       NaN  0.431784  0.834136
13  0.012324  0.970474  0.639654  ...       NaN  0.567671  0.253758  0.412085
14  0.786731  0.140389       NaN  ...  0.368129  0.495894  0.229719  0.231397
15  0.340401       NaN  0.798837  ...  0.150899  0.855886       NaN  0.824663
16  0.765412  0.022801  0.615450  ...  0.248798  0.717613  0.562573  0.399420
17  0.913971  0.793544  0.709638  ...  0.320119       NaN       NaN  0.286503
18  0.480870  0.455641       NaN  ...  0.139095       NaN  0.018263  0.614851
19  0.484978  0.379374       NaN  ...  0.966349  0.822737       NaN  0.659282
20  0.452421  0.907846  0.478727  ...  0.073833  0.888655       NaN       NaN
21       NaN  0.200730       NaN  ...  0.500599  0.848819  0.232277  0.689827
22       NaN  0.441261  0.999146  ...  0.868842  0.629204  0.359470  0.455585
23  0.059907  0.002955  0.071306  ...  0.219956  0.859386  0.606149       NaN
24  0.488232  0.120163  0.570244  ...  0.661546  0.982255  0.173245       NaN
25  0.124787  0.663923       NaN  ...  0.328771  0.172880  0.175572  0.363734
26  0.313059  0.783355  0.792793  ...  0.980423       NaN  0.468967  0.177372
27  0.387318  0.210451  0.873578  ...  0.243761  0.861911  0.300322       NaN
28  0.942161  0.771252  0.758983  ...       NaN  0.370208  0.417268  0.508944
29       NaN  0.512291  0.941388  ...       NaN       NaN  0.598578  0.114358
30  0.752893       NaN       NaN  ...  0.973438  0.179533  0.103862  0.778109
31  0.135041  0.723394  0.992204  ...  0.179708  0.489125  0.872394  0.629422
32  0.412298  0.903254  0.869906  ...       NaN  0.947329  0.279648  0.607586
33  0.099397  0.793810  0.669196  ...  0.809139  0.211571       NaN  0.347198
34  0.060914  0.533699  0.338177  ...       NaN       NaN  0.398914  0.670113
35       NaN  0.500928  0.732630  ...  0.181366       NaN       NaN       NaN
36  0.439264  0.684514       NaN  ...  0.817478  0.080827  0.731484  0.265379
37       NaN  0.180027       NaN  ...  0.355065       NaN       NaN  0.221231
38       NaN  0.694647  0.697757  ...  0.478382  0.236651  0.629173  0.039739
39  0.061423  0.984441  0.727503  ...  0.123723  0.227239  0.946855  0.968615
40       NaN  0.811999  0.163752  ...  0.444978  0.837289       NaN       NaN
41  0.060890  0.523856  0.011919  ...  0.904119  0.729585  0.580778  0.094655
42  0.319995  0.050079  0.220525  ...  0.202440  0.910717  0.596145  0.876660
43  0.397631       NaN  0.546648  ...       NaN  0.321978  0.921522  0.731496
44  0.074519  0.726330  0.919519  ...  0.166298  0.622740  0.090719  0.430525
45  0.095489  0.178354  0.033196  ...  0.577890  0.492759  0.350459  0.178302
46  0.219848  0.492238       NaN  ...       NaN  0.187452  0.593446  0.272784
47       NaN  0.747630  0.755336  ...       NaN  0.652755  0.647720  0.783812
48  0.861637  0.221597  0.324677  ...  0.950266  0.121045  0.849770  0.032420
49  0.122369  0.618551  0.914617  ...  0.164558  0.697053  0.699886  0.073123

          44        45        46        47        48        49
0   0.152650  0.525178  0.912822  0.093171  0.145644       NaN
1   0.652532  0.102297  0.696000  0.898853  0.144122  0.794888
2   0.560163  0.543671  0.756596       NaN  0.101127  0.663285
3   0.296673  0.133133  0.766824  0.705879  0.652344  0.106121
4        NaN  0.191934  0.236856  0.878089  0.932261  0.947983
5        NaN  0.532929  0.728162  0.073904  0.694560  0.822612
6   0.285693  0.884374  0.539227  0.286712  0.980689  0.822647
7   0.286235       NaN  0.850244  0.161349  0.219214  0.983873
8   0.423823  0.373332  0.483133  0.498067  0.083393  0.116659
9   0.596811  0.715891       NaN  0.402390  0.477487  0.288827
10  0.636473  0.250899  0.399721       NaN  0.624237  0.614320
11  0.233724  0.759668  0.769083  0.971888  0.314008  0.030019
12  0.548135  0.553190  0.813396  0.536379  0.000127       NaN
13  0.638639  0.823673  0.776690  0.949189  0.447594  0.463629
14  0.231118  0.509672  0.314040       NaN  0.715107  0.152268
15       NaN  0.014178  0.558238       NaN       NaN  0.787983
16  0.516902  0.711791  0.731509  0.502981  0.635591  0.561311
17  0.896506  0.391598  0.635695       NaN  0.538028  0.816833
18  0.319158  0.803374       NaN  0.470674  0.083576  0.693360
19  0.983123  0.327404  0.390311  0.842699  0.517464  0.103114
20       NaN  0.876421  0.089455  0.842889  0.518277  0.187773
21  0.993455  0.201273  0.658693  0.697275       NaN  0.129244
22  0.384953       NaN  0.987448       NaN       NaN  0.009892
23  0.139073  0.922270  0.302551  0.693394  0.993025  0.523409
24  0.289029  0.379920  0.020553       NaN  0.663350  0.193216
25  0.164286  0.763521       NaN  0.711516       NaN  0.311748
26  0.402149  0.799167  0.634848  0.581219  0.157420  0.062868
27  0.199673  0.039541  0.607404       NaN  0.763428  0.155645
28  0.862887  0.262826  0.402984  0.011035  0.339995  0.651854
29  0.418260  0.138949       NaN  0.359611  0.744118       NaN
30  0.604204  0.442874  0.239175  0.514285       NaN  0.825703
31  0.709846       NaN  0.705039  0.932905  0.152516  0.171563
32  0.720595  0.223389  0.862423  0.449840       NaN  0.770953
33  0.182086  0.840005  0.420938  0.217017  0.778638  0.665072
34  0.430031  0.101507  0.268697       NaN  0.900844  0.368550
35  0.624736  0.795644  0.848957  0.790382       NaN  0.801918
36       NaN  0.804219  0.349022  0.987477  0.786310  0.442565
37       NaN  0.367756       NaN       NaN  0.843664       NaN
38       NaN  0.597114  0.754308  0.030887  0.991270  0.859302
39  0.841526       NaN  0.558305  0.951844  0.273145  0.616819
40       NaN  0.323024  0.242491  0.262155  0.602665  0.422409
41  0.048038  0.962112  0.979081  0.252334       NaN  0.692723
42  0.127756  0.824321  0.355344  0.453036  0.001412  0.987476
43  0.507344  0.724195  0.293664  0.926032       NaN  0.285685
44  0.903369       NaN  0.311812  0.213573  0.887514  0.359055
45  0.071896       NaN  0.066092  0.563325       NaN  0.075737
46  0.530655  0.054354  0.029919  0.065832  0.376575  0.086722
47       NaN  0.228598  0.251902       NaN  0.498165  0.508004
48  0.501537       NaN  0.974523  0.662008  0.576357  0.971532
49  0.140358  0.755989  0.000905  0.907989  0.345090  0.051698

[50 rows x 50 columns]

In [20]:
df4 = pd.DataFrame(np.random.rand(50,50))
df5 = np.random.rand(50,50) < 0.2
df4[df5]=np.nan
df4

,0,1,2,3,4,5,6,7,8,9,...,40,41,42,43,44,45,46,47,48,49
0,0.851428,NaN,0.406073,0.660073,0.794169,0.488605,0.690831,0.158213,0.425231,0.412023,...,0.074942,0.277884,0.640888,0.589639,NaN,0.276756,0.196504,0.584674,NaN,NaN
1,0.719154,NaN,0.966275,0.228677,0.584229,0.957153,0.690577,NaN,0.194527,0.646447,...,0.608006,0.520268,0.785153,NaN,NaN,0.689051,NaN,0.084333,0.491198,0.491196
2,0.356139,0.483538,0.592071,0.319383,NaN,0.132353,0.456544,0.718252,NaN,0.065805,...,0.149001,0.829373,0.395903,0.887687,0.330027,0.938513,0.167916,NaN,0.836620,NaN
3,0.499787,0.140323,0.560505,NaN,0.604912,0.475288,0.401473,0.823364,0.546190,NaN,...,0.050531,0.814789,0.836164,0.576056,NaN,0.551620,0.910661,0.866934,0.043158,0.476087
4,0.040011,NaN,0.391543,0.008935,0.185620,0.924388,0.336755,0.131830,0.610622,0.221658,...,NaN,0.950167,0.985157,0.260781,0.076968,0.779570,0.612320,NaN,NaN,NaN
5,0.307783,0.706773,NaN,0.282244,0.544666,0.349754,0.414697,0.692758,0.708784,NaN,...,0.346575,0.595745,0.049434,0.204390,0.607900,0.887094,0.451371,0.440062,NaN,0.967398
6,0.844631,NaN,NaN,0.336502,NaN,0.507019,0.773484,NaN,NaN,0.803752,...,0.701997,0.395910,0.919590,0.877219,0.053157,0.144715,NaN,0.395142,0.619127,0.985928
7,0.033353,0.555769,0.180214,0.509145,0.421614,0.346218,0.080158,0.461590,0.857802,NaN,...,0.164265,0.480750,0.482253,0.735521,0.755190,0.471014,0.804588,0.122364,0.976538,NaN
8,0.511613,0.162527,0.253041,0.984737,0.526304,0.355458,0.931317,0.953211,0.304774,NaN,...,0.099681,0.841895,0.595878,NaN,0.982502,0.727135,0.706026,0.096192,0.557188,0.258160
9,0.835034,0.488157,0.238482,0.592591,0.334288,0.072376,NaN,0.073954,0.598546,0.475524,...,0.205295,0.043739,0.125348,0.935053,0.028411,0.306002,NaN,0.569927,0.229153,NaN
10,0.909032,0.668701,0.552462,0.494705,NaN,0.759956,0.017976,0.147835,0.211466,NaN,...,0.532540,0.371438,0.028677,0.900857,0.238230,0.988755,NaN,0.896209,0.417829,0.391735
11,0.906649,0.328744,0.100892,0.325513,0.426405,0.029579,0.129792,0.332071,0.920472,0.419763,...,NaN,0.002925,0.240096,0.321957,0.235836,0.513434,0.371984,0.012021,0.079303,0.693867
12,0.185670,0.085418,0.921104,0.899097,NaN,0.038223,0.431357,0.515490,0.584739,0.251360,...,NaN,0.456927,0.740552,NaN,NaN,0.969831,0.628484,0.334755,0.516452,0.110413
13,0.556336,0.328138,NaN,0.361683,0.464084,0.074371,0.565514,0.038401,0.962249,NaN,...,0.804506,0.163636,0.192877,0.933998,0.420954,0.118607,0.740469,0.252337,0.163511,NaN
14,0.312287,0.765057,0.071119,0.879027,0.060850,NaN,0.751570,0.282099,0.541042,0.577649,...,0.841042,0.842059,0.996313,NaN,0.624549,0.236578,0.224057,NaN,0.297083,0.604564
15,0.917915,0.454209,0.471763,0.857447,NaN,0.459202,0.449838,0.188317,0.412305,NaN,...,0.243469,0.725360,0.679846,0.467983,0.677158,0.715145,0.974151,NaN,0.643504,NaN
16,0.015864,0.890276,0.488694,0.454127,0.131756,0.631181,0.967932,0.600513,0.879419,0.701288,...,0.764124,NaN,0.130530,NaN,0.980394,0.719568,0.361758,0.605402,0.020205,0.079265
17,NaN,0.160769,0.897978,0.035486,0.597244,0.335114,0.871253,0.152171,0.754345,0.733160,...,0.367998,0.148729,0.953031,0.389009,NaN,0.947348,NaN,0.923436,0.806004,0.512121
18,0.923311,0.312595,0.386476,NaN,0.115179,0.770585,0.288370,0.197348,0.548164,0.276974,...,0.419574,0.665901,NaN,0.757663,0.659791,0.770220,0.083628,NaN,0.071659,0.746258
19,0.284354,0.633446,0.988317,NaN,NaN,0.302723,0.688638,0.984683,0.706144,NaN,...,0.410676,0.102696,0.854435,0.205020,0.887596,NaN,0.497289,NaN,0.563284,0.059413
20,NaN,0.457914,0.577211,0.863318,0.130939,0.741325,0.633122,NaN,NaN,0.669673,...,0.611810,0.847527,0.917347,0.098398,0.633583,0.088964,NaN,0.927596,0.201626,0.469105
21,NaN,0.818834,0.278275,0.185842,0.204866,NaN,NaN,NaN,0.459006,0.404151,...,0.783720,0.420183,0.826409,NaN,NaN,0.000926,0.122716,0.550163,0.630530,0.801668
22,NaN,0.116080,0.433362,NaN,NaN,NaN,NaN,0.727080,0.451756,0.253820,...,0.787054,0.290230,NaN,0.158402,0.552656,0.234424,0.215077,NaN,NaN,0.528314
23,NaN,0.275608,0.758337,0.616396,0.053839,0.915846,0.268045,0.571232,NaN,0.522545,...,0.503995,0.890902,0.524416,0.655352,NaN,0.294829,0.159681,0.891298,0.723371,0.444388
24,0.202921,0.266265,NaN,0.208572,0.929611,0.180708,0.768716,NaN,0.218974,NaN,...,0.720469,NaN,0.776050,0.126929,0.353565,0.327504,0.945305,NaN,0.474771,0.237111
25,NaN,NaN,0.744916,0.595478,0.990766,NaN,0.759087,NaN,0.961307,0.957598,...,0.666540,0.767859,NaN,0.116095,0.838920,0.944793,NaN,0.995632,NaN,0.703269
26,0.661437,0.743510,NaN,0.775985,0.681748,0.053140,0.761645,0.563350,0.562399,0.601317,...,0.220786,NaN,0.649515,0.839938,0.769918,0.205867,NaN,0.913922,0.018701,0.363380
27,0.483918,0.711898,NaN,0.409077,0.773076,NaN,0.225915,NaN,0.996492,0.142208,...,0.392986,0.337021,NaN,NaN,0.495454,0.847815,NaN,0.377161,0.766050,0.914046
28,0.298201,0.175154,0.905742,0.561379,0.474564,0.667559,0.974251,0.977381,0.715768,0.851840,...,0.790430,0.342571,0.112214,0.144889,0.345340,0.779201,0.306921,0.955677,0.422291,0.903251
29,0.366347,NaN,0.868086,0.149315,NaN,0.365062,0.675191,NaN,NaN,0.066155,...,0.344051,NaN,0.504934,0.630255,0.010922,0.888153,0.407775,0.578318,0.628853,0.748978
30,0.121374,NaN,0.626031,0.983232,NaN,0.102174,0.245561,NaN,0.942596,0.178164,...,0.594485,0.559316,0.983211,0.422556,0.432030,0.363476,NaN,0.920473,0.098325,0.866686
31,0.956905,0.642649,NaN,0.341567,0.282009,NaN,0.520594,0.990529,0.821397,NaN,...,NaN,0.654724,0.710690,NaN,0.326334,0.795252,0.690166,0.784775,NaN,0.645382
32,0.041487,0.809350,0.506539,0.440656,0.541432,0.803597,0.366657,NaN,0.104264,0.791426,...,NaN,0.167291,0.950940,0.754903,NaN,0.318550,0.547283,0.023045,0.793864,0.750095
33,0.719042,0.848026,0.130147,0.580125,0.421331,0.963337,NaN,0.286814,0.773726,0.020345,...,0.269614,0.352102,0.278451,0.008643,0.280912,0.667506,0.339274,NaN,0.480872,0.141786
34,0.461443,0.501517,0.538704,0.240193,0.159597,0.039937,0.352885,0.569693,0.974047,0.127424,...,0.953608,0.564284,0.142541,0.070196,0.759292,0.553818,0.263880,0.794878,0.545280,0.162854
35,0.350129,0.100063,0.474909,0.119047,0.891295,0.966477,0.603933,0.498163,0.343649,0.043160,...,0.374301,0.343618,0.117808,NaN,NaN,0.311824,0.583448,0.824226,0.070854,0.736644
36,0.670224,0.298304,0.919924,0.987581,0.002001,0.988971,0.522293,0.806565,0.697668,0.656004,...,NaN,0.777920,0.244318,0.320449,0.242849,0.605704,0.818768,0.403713,0.783944,0.577445
37,0.779772,0.529238,0.846685,0.683741,0.943044,0.090093,0.545477,NaN,0.703001,0.354956,...,0.358692,0.083723,0.633898,0.854364,0.820860,0.201024,0.631452,0.771023,0.671959,NaN
38,0.630263,0.980097,0.499963,NaN,0.261393,NaN,0.329042,0.317101,0.041227,0.098086,...,0.025140,NaN,0.721867,0.559390,NaN,0.893005,0.403505,0.215583,NaN,0.611692
39,NaN,0.125931,NaN,0.096273,0.216808,0.487925,0.746035,0.633354,0.006845,0.847060,...,0.035840,0.159503,0.477211,0.923882,0.392941,0.015811,0.892028,0.578173,0.971309,0.033612
40,0.781986,0.055027,0.690742,0.094805,0.774098,0.045548,0.200948,NaN,NaN,NaN,...,0.059294,0.734953,0.655338,0.214225,0.756202,0.932100,0.104207,0.451270,0.310465,0.392492
41,0.954337,0.858623,NaN,0.622470,0.271860,0.894680,0.207605,0.649877,0.171977,0.618388,...,0.007885,0.200299,0.883587,0.848483,0.086516,0.760431,NaN,0.656890,0.735195,0.180853
42,0.178810,0.943426,0.465047,NaN,0.877202,0.435175,0.337133,0.787857,0.222492,0.090278,...,0.587401,0.785193,NaN,0.121907,0.605851,NaN,0.257070,0.267136,0.557597,0.355893
43,0.755066,NaN,NaN,0.405355,NaN,0.852201,0.533678,0.477150,0.948156,NaN,...,0.716465,0.145290,0.036382,0.538931,NaN,0.404409,0.997149,0.572558,0.622652,0.994527
44,NaN,0.991895,NaN,NaN,NaN,0.514829,0.963809,0.907624,0.421667,0.548319,...,NaN,0.374699,NaN,0.336036,NaN,NaN,NaN,NaN,NaN,0.532602
45,0.482237,0.056791,0.620475,NaN,0.888628,0.746209,NaN,NaN,NaN,0.912122,...,NaN,0.386149,0.462439,NaN,0.183913,0.021631,NaN,0.708447,0.078813,NaN
46,0.331542,0.073696,0.510068,0.390638,0.036915,0.971883,NaN,0.358282,0.360425,NaN,...,0.740464,NaN,0.836043,NaN,0.035301,0.602572,0.439007,NaN,0.964289,NaN
47,NaN,NaN,0.090552,0.080071,0.911732,0.573128,0.254236,0.394718,0.258983,0.056474,...,NaN,0.245747,NaN,0.321720,NaN,0.651864,0.976685,0.686327,0.221008,0.356203
48,0.158854,0.982175,NaN,NaN,NaN,0.261843,NaN,0.021458,0.764038,NaN,...,0.450084,0.087066,0.779461,NaN,0.102200,0.815146,0.732303,0.467844,NaN,0.349042
49,0.316152,0.019484,0.315729,0.638764,0.559754,0.753629,0.913191,NaN,0.058386,0.653213,...,NaN,0.203726,0.263562,0.567312,0.669274,0.660118,0.318471,0.413668,0.655184,0.893556