In [1]:
import numpy as np
import pandas as pd
df_customer=pd.read_csv("customers.csv")
df_sales=pd.read_csv("sales.csv")
df_sales

,order_id,date,region,product,category,customer_type,quantity,price,discount,sales
0,1,2024-04-12,East,Laptop,Electronics,Returning,8,590,0.09,4295.20
1,2,2024-12-14,South,Monitor,Accessories,Returning,2,262,0.18,429.68
2,3,2024-09-27,North,Phone,Accessories,New,5,512,0.09,2329.60
3,4,2024-04-16,West,Mouse,Electronics,Returning,1,485,0.09,441.35
4,5,2024-03-12,West,Phone,Electronics,Returning,7,332,0.22,1812.72
...,...,...,...,...,...,...,...,...,...,...
495,496,2024-11-20,South,Mouse,Accessories,Returning,6,314,0.23,1450.68
496,497,2024-01-04,North,Phone,Accessories,Returning,9,369,0.23,2557.17
497,498,2024-01-16,South,Keyboard,Electronics,Returning,6,722,0.14,3725.52
498,499,2024-10-06,North,Phone,Accessories,Returning,2,1449,0.12,2550.24
499,500,2024-12-01,North,Monitor,Electronics,New,2,869,0.09,1581.58

In [2]:
df_customer.info()
df_sales.info()
df_sales.duplicated().sum()
df_sales["date"]=pd.to_datetime(df_sales["date"])
df_sales.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 2 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   order_id         500 non-null    int64
 1   customer_rating  500 non-null    int64
dtypes: int64(2)
memory usage: 7.9 KB
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       500 non-null    int64
 1   date           500 non-null    str
 2   region         500 non-null    str
 3   product        500 non-null    str
 4   category       500 non-null    str
 5   customer_type  500 non-null    str
 6   quantity       500 non-null    int64
 7   price          500 non-null    int64
 8   discount       500 non-null    float64
 9   sales          500 non-null    float64
dtypes: float64(2), int64(3), str(5)
memory usage: 39.2 KB
<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   order_id       500 non-null    int64
 1   date           500 non-null    datetime64[us]
 2   region         500 non-null    str
 3   product        500 non-null    str
 4   category       500 non-null    str
 5   customer_type  500 non-null    str
 6   quantity       500 non-null    int64
 7   price          500 non-null    int64
 8   discount       500 non-null    float64
 9   sales          500 non-null    float64
dtypes: datetime64[us](1), float64(2), int64(3), str(4)
memory usage: 39.2 KB

In [3]:
df_sales.groupby("region")["sales"].sum()
df_sales.groupby("customer_type")["sales"].sum()

customer_type
New          793937.36
Returning    872592.42
Name: sales, dtype: float64

In [4]:
df_merged=pd.merge(df_sales,df_customer,on="order_id")
df_merged.columns

Index(['order_id', 'date', 'region', 'product', 'category', 'customer_type',
       'quantity', 'price', 'discount', 'sales', 'customer_rating'],
      dtype='str')

In [5]:
df_merged=pd.pivot_table(df_merged,values="sales",index="region",columns="customer_type",aggfunc="mean")
df_merged

customer_type          New    Returning
region
East           3518.489123  3630.652951
North          3301.913836  3436.063846
South          3388.539808  2905.541406
West           3090.170175  3399.223448